# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48f9765636dfaa0e23e72125ff40382e518fde8555997eed9931c50b1c2d8155c20746006105f837e16bab6f7436b20a98480dbeec36e140680731aa87fafe7

test:
  secret_key_base: ccaf5db323245909f1c6e4cfc51a3cdf8afdd3b4966df46bcea4a78d1a4b708969a4d6d9cbfd87c02616a83f92393b6ea61676849a26c0cc3ec30a52b666210b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
