# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104ae55c0c2ab3802841fdbcae7932ff9071e63c06f8b097b90301b68cf62c0a0eac954f2460d489d3c5730ab9155f58bcfe533c71642d69ccfb943dc7889116

test:
  secret_key_base: 4a0ebd79e602404c63bba8bde46b979de90d45bd1b42b093bb48017eb215f3c9dbbc01a62adbb2e1421d433f963443588f63680710fdbf42b92fbc3581b3d2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
