# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d68750abac52ad091883f0f274a66d10c9bad29510c091d17f1df3f57747f962825db283b943acb37f0b0f48b357f7b9ae952139df1428fe85120950426468f

test:
  secret_key_base: 02c918a242a4aea964a2441e9872775ff8d278d150893e7ccee581ccc159d80162434ce5ffa5b4d474409c4e5f26297cc94761af8d85c2fcd401d6790c2b6d72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
